name: Marketplace Mailer

on:
  push:
  workflow_dispatch:

jobs:
  send_mail:
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: tunyasystems.co.ke
          server_port: 465
          username: omondi@tunyasystems.co.ke
          password: 'Gorm@hia1968'
          subject: Test Email from Omondi (Marketplace Action)
          body: This is a test email sent from tunyasystems.co.ke via Marketplace Action.
          to: oqayuve892@gmail.com
          from: omondi@tunyasystems.co.ke
          secure: true
